version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_rentals_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rentals_db
      MYSQL_USER: rental_user
      MYSQL_PASSWORD: rental_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: